config:
  token: 5XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  id: 111111111
  args: no # If set to "yes", allows to send arguments with bot commands
           # WARNING! Could be dangerous, if someone gets access to your bot

commands:
- name: la
  exec: "ls -al"
  desc: "List all files"

- name: ping
  exec: "ping -c 3 8.8.8.8"
  desc: "Ping Google DNS"